
/*
 * Do not edit this file, it is autogenerated.
 * Edit menu_cfg.json instead, then type "make".
 */
#include "menu.h"

// Pano
// New Pano
int onStart(int);

static OptionSelector menu_new_pano("New Pano", NULL, 0, 0 * sizeof(int), onStart);

// Repeat Last
int onRepeat(int);

static OptionSelector menu_repeat_last("Repeat Last", NULL, 0, 0 * sizeof(int), onRepeat);

// 360 Pano
int on360(int);

static OptionSelector menu_360_pano("360 Pano", NULL, 0, 0 * sizeof(int), on360);

// Last Pano Info
int onPanoInfo(int);

static OptionSelector menu_last_pano_info("Last Pano Info", NULL, 0, 0 * sizeof(int), onPanoInfo);

// Manual Horiz FOV
extern volatile int horiz;

static RangeSelector menu_manual_horiz_fov("Manual Horiz FOV", &horiz, 120, 1 * sizeof(int), NULL, 10, 360, 10);

// Manual Vert FOV
extern volatile int vert;

static RangeSelector menu_manual_vert_fov("Manual Vert FOV", &vert, 90, 2 * sizeof(int), NULL, 10, 180, 10);


static const PROGMEM BaseMenu* const menu_pano_opts[] = {&menu_new_pano, &menu_repeat_last, &menu_360_pano, &menu_last_pano_info, &menu_manual_horiz_fov, &menu_manual_vert_fov};
Menu menu_pano("Pano", 6, menu_pano_opts);

// Camera
// Focal Len
extern volatile int focal;

static const PROGMEM int menu_focal_len_values[16] = {12, 14, 16, 20, 24, 28, 35, 50, 75, 105, 200, 300, 400, 450, 500, 600};
static ListSelector menu_focal_len("Focal Len", &focal, 35, 3 * sizeof(int), NULL, 16, menu_focal_len_values);

// Shutter
extern volatile int shutter;
static const PROGMEM char menu_shutter_name_0[] = "1/100";
static const PROGMEM char menu_shutter_name_1[] = "1/50";
static const PROGMEM char menu_shutter_name_2[] = "1/25";
static const PROGMEM char menu_shutter_name_3[] = "1/10";
static const PROGMEM char menu_shutter_name_4[] = "1/4";
static const PROGMEM char menu_shutter_name_5[] = "0.5s";
static const PROGMEM char menu_shutter_name_6[] = "1s";
static const PROGMEM char menu_shutter_name_7[] = "2s";
static const PROGMEM char menu_shutter_name_8[] = "4s";
static const PROGMEM char menu_shutter_name_9[] = "8s";
static const PROGMEM char menu_shutter_name_10[] = "MANUAL";

static const PROGMEM char * const menu_shutter_names[11] = {menu_shutter_name_0, menu_shutter_name_1, menu_shutter_name_2, menu_shutter_name_3, menu_shutter_name_4, menu_shutter_name_5, menu_shutter_name_6, menu_shutter_name_7, menu_shutter_name_8, menu_shutter_name_9, menu_shutter_name_10};
static const PROGMEM int menu_shutter_values[11] = {10, 20, 40, 100, 250, 500, 1000, 2000, 4000, 8000, 0};
static NamedListSelector menu_shutter("Shutter", &shutter, 10, 4 * sizeof(int), NULL, 11, menu_shutter_names, menu_shutter_values);

// Delay
extern volatile int pre_shutter;
static const PROGMEM char menu_delay_name_0[] = "0.1s";
static const PROGMEM char menu_delay_name_1[] = "0.5s";
static const PROGMEM char menu_delay_name_2[] = "1s";
static const PROGMEM char menu_delay_name_3[] = "2s";
static const PROGMEM char menu_delay_name_4[] = "4s";
static const PROGMEM char menu_delay_name_5[] = "8s";

static const PROGMEM char * const menu_delay_names[6] = {menu_delay_name_0, menu_delay_name_1, menu_delay_name_2, menu_delay_name_3, menu_delay_name_4, menu_delay_name_5};
static const PROGMEM int menu_delay_values[6] = {100, 500, 1000, 2000, 4000, 8000};
static NamedListSelector menu_delay("Delay", &pre_shutter, 100, 5 * sizeof(int), NULL, 6, menu_delay_names, menu_delay_values);

// Processing Wait
extern volatile int post_wait;
static const PROGMEM char menu_processing_wait_name_0[] = "0.1s";
static const PROGMEM char menu_processing_wait_name_1[] = "0.25s";
static const PROGMEM char menu_processing_wait_name_2[] = "0.5s";
static const PROGMEM char menu_processing_wait_name_3[] = "1s";
static const PROGMEM char menu_processing_wait_name_4[] = "2s";
static const PROGMEM char menu_processing_wait_name_5[] = "4s";
static const PROGMEM char menu_processing_wait_name_6[] = "8s";

static const PROGMEM char * const menu_processing_wait_names[7] = {menu_processing_wait_name_0, menu_processing_wait_name_1, menu_processing_wait_name_2, menu_processing_wait_name_3, menu_processing_wait_name_4, menu_processing_wait_name_5, menu_processing_wait_name_6};
static const PROGMEM int menu_processing_wait_values[7] = {100, 250, 500, 1000, 2000, 4000, 8000};
static NamedListSelector menu_processing_wait("Processing Wait", &post_wait, 100, 6 * sizeof(int), NULL, 7, menu_processing_wait_names, menu_processing_wait_values);

// Shutter Mode
extern volatile int long_pulse;
static const PROGMEM char menu_shutter_mode_name_0[] = "Normal";
static const PROGMEM char menu_shutter_mode_name_1[] = "Cont Bkt";

static const PROGMEM char * const menu_shutter_mode_names[2] = {menu_shutter_mode_name_0, menu_shutter_mode_name_1};
static const PROGMEM int menu_shutter_mode_values[2] = {0, 1};
static NamedListSelector menu_shutter_mode("Shutter Mode", &long_pulse, 0, 7 * sizeof(int), NULL, 2, menu_shutter_mode_names, menu_shutter_mode_values);

// Shots #
extern volatile int shots;

static RangeSelector menu_shots__("Shots #", &shots, 1, 8 * sizeof(int), NULL, 1, 5, 1);

// Aspect
extern volatile int aspect;
static const PROGMEM char menu_aspect_name_0[] = "P 2:3";
static const PROGMEM char menu_aspect_name_1[] = "L 3:2";

static const PROGMEM char * const menu_aspect_names[2] = {menu_aspect_name_0, menu_aspect_name_1};
static const PROGMEM int menu_aspect_values[2] = {23, 32};
static NamedListSelector menu_aspect("Aspect", &aspect, 23, 9 * sizeof(int), NULL, 2, menu_aspect_names, menu_aspect_values);

// Test Shutter
int onTestShutter(int);

static OptionSelector menu_test_shutter("Test Shutter", NULL, 0, 0 * sizeof(int), onTestShutter);


static const PROGMEM BaseMenu* const menu_camera_opts[] = {&menu_focal_len, &menu_shutter, &menu_delay, &menu_processing_wait, &menu_shutter_mode, &menu_shots__, &menu_aspect, &menu_test_shutter};
Menu menu_camera("Camera", 8, menu_camera_opts);

// Motors
extern volatile int motors_enable;
static const PROGMEM char menu_motors_name_0[] = "On";
static const PROGMEM char menu_motors_name_1[] = "Off";

static const PROGMEM char * const menu_motors_names[2] = {menu_motors_name_0, menu_motors_name_1};
static const PROGMEM int menu_motors_values[2] = {1, 0};
static NamedListSelector menu_motors("Motors", &motors_enable, 0, 0 * sizeof(int), NULL, 2, menu_motors_names, menu_motors_values);

// Display
extern volatile int display_invert;
static const PROGMEM char menu_display_name_0[] = "Dark";
static const PROGMEM char menu_display_name_1[] = "Bright";

static const PROGMEM char * const menu_display_names[2] = {menu_display_name_0, menu_display_name_1};
static const PROGMEM int menu_display_values[2] = {0, 1};
static NamedListSelector menu_display("Display", &display_invert, 0, 0 * sizeof(int), NULL, 2, menu_display_names, menu_display_values);


static const PROGMEM BaseMenu* const menu_opts[] = {&menu_pano, &menu_camera, &menu_motors, &menu_display};
Menu menu("Main Menu", 4, menu_opts);

